# ------------------------------------------------------------
# ingress-nginx-values.yaml
# ------------------------------------------------------------
# This file contains the Helm values used to install ingress-nginx
# in the RabbitMQ Kubernetes Lab environment.
#
# It replaces an internal FluxCD HelmRelease:
#   - No FluxCD required
#   - No GitRepository references
#   - Safe for public GitHub usage
#
# ------------------------------------------------------------
# 📌 HOW TO INSTALL INGRESS-NGINX IN THIS LAB
# ------------------------------------------------------------
#
# 1. Add the official ingress-nginx Helm repo:
#      helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
#      helm repo update
#
# 2. Create the namespace (if it does not exist):
#      kubectl create namespace ingress-nginx --dry-run=client -o yaml | kubectl apply -f -
#
# 3. Install ingress-nginx using this values.yaml:
#      helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
#        -n ingress-nginx \
#        -f infrastructure/base/ingress-nginx/ingress-nginx-values.yaml
#
# 4. Verify:
#      kubectl get pods -n ingress-nginx
#      kubectl get svc -n ingress-nginx
#
# ------------------------------------------------------------
# Controller configuration
# ------------------------------------------------------------

controller:
  allowSnippetAnnotations: true

  metrics:
    enabled: true
    service:
      annotations:
        prometheus.io/port: "10254"
        prometheus.io/scrape: "true"

  replicaCount: 2

  topologySpreadConstraints:
    - labelSelector:
        matchLabels:
          app.kubernetes.io/component: controller
          app.kubernetes.io/instance: ingress-nginx
          app.kubernetes.io/name: ingress-nginx
      maxSkew: 1
      topologyKey: topology.kubernetes.io/zone
      whenUnsatisfiable: ScheduleAnyway

# ------------------------------------------------------------
# Default Backend
# ------------------------------------------------------------
defaultBackend:
  enabled: true

# ------------------------------------------------------------
# TCP Forwarding
# Useful when exposing non-HTTP services via ingress-nginx
# ------------------------------------------------------------
tcp:
  "1725": "default/logstash:1725"
  "1726": "default/logstash:1726"
